PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?country ?capital
WHERE {
  ?country a 		        dbo:Country ;
		       dbo:capital  ?capital .
  ?capital a 		        dbo:City ;
    	     dbo:areaCode "020" .
}
