PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT ?city ?capital
WHERE {
  ?city  dbo:areaCode  "020" .
  OPTIONAL {
     ?capital  dbo:capital  ?city .  
  }
}
