PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT ?city ?population
WHERE {
  ?city dbo:areaCode	    "020" ;
 	    dbo:populationTotal ?population .
  FILTER (?population > 500000)
} 
