PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?city
WHERE {
 ?city      dbo:areaCode	"020" .
 ?capital   dbo:capital     ?city
}
