PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT ?g
WHERE {
  GRAPH ?g {
    dbr:Amsterdam dbo:areaCode [] .
  }
}
