PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
SELECT ?country (COUNT(DISTINCT ?city) AS ?city_count)
WHERE {
  ?country a dbo:Country .
  ?city dbo:country ?country .
}
