PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpediaowl: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
SELECT ?country ?capital
WHERE {
  ?country a dbpediaowl:Country ;
    dbpediaowl:capital ?capital .
  ?capital a dbpediaowl:City ;
    dbp:areaCode	020 .
}
