PREFIX dbpediaowl: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
SELECT ?city ?capitalOf
WHERE {
 ?city dbp:areaCode	020 . 
  OPTIONAL { ?capitalOf dbpediaowl:capital ?city  }
} 