PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpediaowl: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
SELECT ?g 
WHERE {
  GRAPH ?g {
    dbpedia:Amsterdam dbpediaowl:areaCode [] .
  }
}